name: Build Multi-Platform Natives abd Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Windows Build
      - name: Compile Windows DLL
        if: matrix.os == 'windows-latest'
        run: |
          # Download the dev kit
          curl -L -o mpv-sdk.7z https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20260304/mpv-dev-x86_64-20260304-git-c401ef9.7z
          7z x mpv-sdk.7z -ompv-dev

          gcc -shared -o native_render.dll auraplayer-core/src/main/c/native_render.c `
            -Impv-dev/include `
            -I"${{ env.JAVA_HOME }}/include" `
            -I"${{ env.JAVA_HOME }}/include/win32" `
            -L"${{ env.JAVA_HOME }}/lib" `
            -ljawt `
            mpv-dev/libmpv.dll.a

          New-Item -ItemType Directory -Force -Path "auraplayer-core/src/main/resources/nativelibs/windows-x64"
          Move-Item -Force native_render.dll auraplayer-core/src/main/resources/nativelibs/windows-x64/
          Copy-Item -Force mpv-dev/libmpv-2.dll auraplayer-core/src/main/resources/nativelibs/windows-x64/

      # Linux Build
      - name: Compile Linux SO
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Install the MPV development headers and library
          sudo apt-get update
          sudo apt-get install -y libmpv-dev
          gcc -fPIC -shared -o libnative_render.so auraplayer-core/src/main/c/native_render.c \
            -I"${{ env.JAVA_HOME }}/include" \
            -I"${{ env.JAVA_HOME }}/include/linux" \
            -L"${{ env.JAVA_HOME }}/lib" \
            -ljawt \
            -lmpv
          
          mkdir -p auraplayer-core/src/main/resources/nativelibs/linux-x64
          mv libnative_render.so auraplayer-core/src/main/resources/nativelibs/linux-x64/

      # MacOS Build
      - name: Compile MacOS Dylib
        if: matrix.os == 'macos-latest'
        run: |
          brew install mpv
          
          JAWT_PATH=$(find "${{ env.JAVA_HOME }}" -name "libjawt.dylib" -exec dirname {} \;)
          BREW_PATH=$(brew --prefix)
          echo "JAWT found at: $JAWT_PATH"
          echo "Homebrew found at: $BREW_PATH"
          
          clang -dynamiclib -o libnative_render.dylib auraplayer-core/src/main/c/native_render.c \
            -I"${{ env.JAVA_HOME }}/include" \
            -I"${{ env.JAVA_HOME }}/include/darwin" \
            -I"$BREW_PATH/include" \
            -L"$JAWT_PATH" \
            -L"${{ env.JAVA_HOME }}/lib" \
            -L"$BREW_PATH/lib" \
            -ljawt -lmpv \
            -framework AppKit \
            -framework QuartzCore \
            -framework Foundation \
            -arch arm64
          
          mkdir -p auraplayer-core/src/main/resources/nativelibs/macos-x64
          mv libnative_render.dylib auraplayer-core/src/main/resources/nativelibs/macos-x64/

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build Fat JAR
        run: ./gradlew :auraplayer-core:jar

      - name: Upload Native Binary to Workflow
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.os }}
          path: auraplayer-core/src/main/resources/nativelibs/

  publish:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download all natives
        uses: actions/download-artifact@v4
        with:
          path: auraplayer-core/src/main/resources/nativelibs/
          merge-multiple: true

      - name: Debug - List Resource Folder
        run: ls -R auraplayer-core/src/main/resources/nativelibs/

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Debug Secrets Presence
        run: |
          if [ -z "${{ secrets.GPG_SIGNING_KEY }}" ]; then
            echo "ERROR: GPG_SIGNING_KEY is empty!"
          else
            echo "SUCCESS: GPG_SIGNING_KEY is set."
          fi

      - name: Publish to Maven Central (Sonatype)
        run: ./gradlew publishToMavenCentral -Paura_version=${GITHUB_REF_NAME#v}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            auraplayer-core/build/libs/*.jar
            auraplayer-compose/build/libs/*.jar
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}